### ISSUE TITLE
With the newest Update i get many Logmessages

### ISSUE THREAD

**Issue by HerrBeef** [Harmonised7/explosiont#1]
Hi,

i've updated the mod to 2.1.1 and since that i get many logmessages containing:
[harmonised.explosiont.events.WorldTickHandler:handleWorldTick:49]: null b (not always null b sometimes bigger object + b)
every tick i get this message on the server and on the client (when singleplayer).

**Comment by WenXin20** [comment]
I'm having the same issue, the following is constantly being spammed in my server log. I'm using Forge v31.2.19.
`[20Jun2020 23:09:04.479] [Server thread/INFO] [STDOUT/]: [harmonised.explosiont.events.WorldTickHandler:handleWorldTick:49]: null b`

**Comment by Harmonised7** [comment]
Been fixed, forgot to reply c: Thanks for report!
